### ISSUE TITLE
The example from README fails on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [cloudflightio/python-dlinfo#98]
This program fails:
```
from dlinfo import DLInfo
import ctypes

lib = ctypes.cdll.LoadLibrary(ctypes.util.find_library('c'))
dlinfo = DLInfo(lib)
print(dlinfo.path)
```

```
Traceback (most recent call last):
  File "/usr/ports/devel/py-dlinfo/x.py", line 8, in <module>
    print(dlinfo.path)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dlinfo/_glibc.py", line 46, in path
    return self._linkmap.contents.l_name.decode(sys.getdefaultencoding())
           ^^^^^^^^^^^^^^^^^^^^^^
ValueError: NULL pointer access
```

**Comment by fphammerle** [comment]
Sorry, I do not have a FreeBSD system for debugging. Please submit a pull request if you find a fix.
